### ISSUE TITLE
[FR] allow to specify `--tags` & `--skip-tags`

### ISSUE THREAD

**Issue by timgreen** [roles-ansible/check-ansible-debian-latest-action#1]
My playbook contains some roles that is not possible to pass in a vm.

And same requests for other check-ansible-foo-action(s). And thanks for make those convenient actions.

**Comment by timgreen** [comment]
PS, my current workaround is put the commandline flags inside the "$TARGETS".

https://github.com/timgreen/HomeConfig/commit/372b27a2305dc7dc8de473e695ded6d59038baa7

So one solution is just update the doc & example to explicitly mention this usage is allowed.

**Comment by DO1JLR** [comment]
I like the idea. I think I will add a option for more optional parameters when I find the time after my vacation.

Thanks for opening the issue and sharing your workaround.
